### ISSUE TITLE
ValueError: zero-size array to reduction operation fmin which has no identity

### ISSUE THREAD

**Issue by asapsmc** [RomainPastureau/find_delay#2] opened 2024-08-28 20:31 UTC
**Describe the bug**
I'm getting message `ValueError: zero-size array to reduction operation fmin which has no identity`and no image is plotted. 

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen. I'm calling the function like this: 
```
find_delay.find_delay(y_full, y_snippet, sr_full, sr_snippet, compute_envelope=True, window_size_env=1e6, overlap_ratio_env=0.5,
                          resampling_rate=1000, window_size_res=1e7, overlap_ratio_res=0.5, return_delay_format="timedelta",
                          resampling_mode="cubic", plot_figure=True, path_figure="figure_3.png", plot_intermediate_steps=True,
                          verbosity=1)

```
**Screenshots**
This is the output:
<img width="915" alt="image" src="https://github.com/user-attachments/assets/1b28f787-dba7-45a4-b314-c3872306629a">

**Desktop (please complete the following information):**
 - OS: macOS M1 Sonoma 14.5

**Smartphone (please complete the following information):**

**Additional context**
I can run your examples without errors, but these audios produce this error.
I'm uploading a zip with the 2 numpy arrays (saved with `np.savez_compressed`, `y_full` and `y_snippet`, with `sr_full=sr_snippet=8000`.

**Comment by RomainPastureau** [comment] 2024-08-30 15:02
Hi!

First, thank you for using this package and taking the time to open an issue :)

It's the first time I see this error. The first thing I note isthat the max correlation is found before the onset of the main array, meaning the excerpt would start before the array. The detection of excerpts over the edges of the main array is one of the most recent features of the toolbox, so it might be buggy. In your case, does it make sense that the excerpts starts before the first array?

Moreover, could you copy and paste the full error message (indicating the problematic lines in the find_delay module)? That would allow me to pinpoint which parts of the code are causing the issue.

I also see that the display of the timestamp is wrong (-1 day, 23:59:59.463000) - that's another thing I have to correct.

Finally, you mention having uploaded a zip with the two numpy arrays - do you have a link for that? If i can reproduce the error, it would be great!

Thank you!

**Comment by asapsmc** [comment] 2024-08-31 21:31
Hi,

First off, thank you for developing this tool and making it available. I
recently felt the need for something similar, as I have to match some
hundreds of audio files.

Regarding the issue, I’ve tried to upload a zip into your repo (containing
the two numpy arrays sampled at 22kHz), but I suppose it wasn't ready. I'm
trying
 numpy_arrays.npz.zip
<https://drive.google.com/file/d/1utIDLuhmkPCz2eUyfoKAZRvoYwuMS0Jh/view?usp=drive_web>

again now.

Here’s the full error message I encountered from find_delay:

Exception has occurred: ValueError
zero-size array to reduction operation fmin which has no identity

Thanks again and keep up the good work.

**Comment by RomainPastureau** [comment] 2024-09-04 22:46
Hello!

Good news: After investigation, **I found where the error came from!** - it was an oversight from my side. 

The problem did not come from the cross-correlation part, but from the figure plotting. When plotting the figure, the code compares the values in the excerpt to the values in the largest audio, where the excerpt was found to be.

Doing so, even if the amplitudes are different, we can plot their waveform on top of each other, and check visually if they match. 

The issue was that, in the case where the excerpt starts before the onset of the larger audio, or ends after the offset, the indices would become negative (in your case) or larger than the length of the array. I modified this to calculate the difference in amplitude only on the part of the excerpt contained in the larger array.

A few tests seem to show it works with version 2.9 deployed today. Note that this version also allows to pass directly the WAV paths as parameters of `find_delay`, among some other updates!

Let me know if it works for you now, and I will close this issue.

**Comment by asapsmc** [comment] 2024-09-05 11:20
2.9 is not working for me. With those same arrays, I'm getting 
```
Exception has occurred: TypeError
slice indices must be integers or None or have an __index__ method
  File "/Users/MACHINE/PROJECT/src/_test_find_delay_original.py", line 12, in <module>
    find_delay(y_full, y_snippet, sr, sr, compute_envelope=True, window_size_env=1e6, overlap_ratio_env=0.5,
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by RomainPastureau** [comment] 2024-09-05 15:37
2.9 ended up to have a critical bug, my bad. I added a bunch of tests to prevent this from happening in the future. Let me know if 2.10 works!

**Comment by asapsmc** [comment] 2024-09-05 18:09
No, not working, I get the exact same error, probably related to plotting the figure, as I receive the 
```
Computing the correlation... Done.
        Cross-correlation calculated in: 0:00:00.175024
        No correlation over threshold found (max correlation: 0.367) found at sample -11248 (timestamp -0:00:01.406000).

Complete delay finding function executed in: 0:00:02.812627
``` 
and only after that I get the `slice indices must be integers or None or have an __index__ method`. 
There's no need to rush into a new version just for this (I already have a workaround). Take your time and test with my examples if you wish. The sampling rate of both arrays I sent is 8000Hz.

**Comment by RomainPastureau** [comment] 2024-09-05 19:17
I think found the issue - a simple error of float to integer conversion.
I uploaded a new version and added even more tests that include figure generation. Let me know if the problem is solved on your side!

**Closed** 2024-09-12 13:21 UTC
Labels: bug

**Comment by asapsmc** [comment] 2024-09-12 17:40
I've missed the time to check this, but I assume all it's ok. Thanks.

**Comment by RomainPastureau** [comment] 2024-09-13 10:25
I tried it again with the data you provided and it worked this time around - having the tests will prevent similar things to happen in the future, so thank you a lot for your input!
